import { Team } from './types';

export const TEAMS: Team[] = [
  { id: 'turkey', name: 'Türkiye Milli Takımı', colors: ['Red', 'White'], logoUrl: './logos/turkey.png' },
  { id: 'gs', name: 'Galatasaray', colors: ['Yellow', 'Red'], logoUrl: './logos/gs.png' },
  { id: 'fb', name: 'Fenerbahçe', colors: ['Yellow', 'Navy Blue'], logoUrl: './logos/fb.png' },
  { id: 'bjk', name: 'Beşiktaş', colors: ['Black', 'White'], logoUrl: './logos/bjk.png' },
  { id: 'ts', name: 'Trabzonspor', colors: ['Burgundy', 'Blue'], logoUrl: './logos/ts.png' },
  { id: 'bursa', name: 'Bursaspor', colors: ['Green', 'White'], logoUrl: './logos/bursa.png' },
  { id: 'alanya', name: 'Alanyaspor', colors: ['Orange', 'Green'], logoUrl: './logos/alanya.png' },
  { id: 'antalya', name: 'Antalyaspor', colors: ['Red', 'White'], logoUrl: './logos/antalya.png' },
  { id: 'rize', name: 'Çaykur Rizespor', colors: ['Green', 'Blue'], logoUrl: './logos/rize.png' },
  { id: 'eyup', name: 'Eyüpspor', colors: ['Purple', 'Yellow'], logoUrl: './logos/eyup.png' },
  { id: 'karagumruk', name: 'Fatih Karagümrük', colors: ['Red', 'Black'], logoUrl: './logos/karagumruk.png' },
  { id: 'gaziantep', name: 'Gaziantep FK', colors: ['Red', 'Black'], logoUrl: './logos/gaziantep.png' },
  { id: 'gencler', name: 'Gençlerbirliği', colors: ['Red', 'Black'], logoUrl: './logos/gencler.png' },
  { id: 'goztepe', name: 'Göztepe', colors: ['Yellow', 'Red'], logoUrl: './logos/goztepe.png' },
  { id: 'basaksehir', name: 'İstanbul Başakşehir', colors: ['Orange', 'Navy Blue'], logoUrl: './logos/basaksehir.png' },
  { id: 'kasimpasa', name: 'Kasımpaşa', colors: ['Navy Blue', 'White'], logoUrl: './logos/kasimpasa.png' },
  { id: 'kayseri', name: 'Kayserispor', colors: ['Yellow', 'Red'], logoUrl: './logos/kayseri.png' },
  { id: 'kocaeli', name: 'Kocaelispor', colors: ['Green', 'Black'], logoUrl: './logos/kocaeli.png' },
  { id: 'konya', name: 'Konyaspor', colors: ['Green', 'White'], logoUrl: './logos/konya.png' },
  { id: 'samsun', name: 'Samsunspor', colors: ['Red', 'White'], logoUrl: './logos/samsun.png' },
  { id: 'adana', name: 'Adana Demirspor', colors: ['Navy Blue', 'Light Blue'], logoUrl: './logos/adana.png' },
  { id: 'amed', name: 'Amed SK', colors: ['Green', 'Red', 'White'], logoUrl: './logos/amed.png' },
  { id: 'ankara_keci', name: 'Ankara Keçiörengücü', colors: ['Purple', 'White'], logoUrl: './logos/ankara_keci.png' },
  { id: 'bandirma', name: 'Bandırmaspor', colors: ['Burgundy', 'White'], logoUrl: './logos/bandirma.png' },
  { id: 'bodrum', name: 'Bodrum FK', colors: ['Green', 'White'], logoUrl: './logos/bodrum.png' },
  { id: 'bolu', name: 'Boluspor', colors: ['Red', 'White'], logoUrl: './logos/bolu.png' },
  { id: 'corum', name: 'Çorum FK', colors: ['Red', 'Black'], logoUrl: './logos/corum.png' },
  { id: 'erzurum', name: 'Erzurumspor', colors: ['Blue', 'White'], logoUrl: './logos/erzurum.png' },
  { id: 'esenler', name: 'Esenler Erokspor', colors: ['Yellow', 'Green'], logoUrl: './logos/esenler.png' },
  { id: 'hatay', name: 'Hatayspor', colors: ['Burgundy', 'White'], logoUrl: './logos/hatay.png' },
  { id: 'igdir', name: 'Iğdır FK', colors: ['Green', 'White'], logoUrl: './logos/igdir.png' },
  { id: 'istanbul', name: 'İstanbulspor', colors: ['Yellow', 'Black'], logoUrl: './logos/istanbul.png' },
  { id: 'manisa', name: 'Manisa FK', colors: ['Black', 'White'], logoUrl: './logos/manisa.png' },
  { id: 'pendik', name: 'Pendikspor', colors: ['Red', 'White'], logoUrl: './logos/pendik.png' },
  { id: 'sakarya', name: 'Sakaryaspor', colors: ['Green', 'Black'], logoUrl: './logos/sakarya.png' },
  { id: 'sariyer', name: 'Sarıyer', colors: ['Navy Blue', 'White'], logoUrl: './logos/sariyer.png' },
  { id: 'serik', name: 'Serikspor', colors: ['Green', 'White'], logoUrl: './logos/serik.png' },
  { id: 'sivas', name: 'Sivasspor', colors: ['Red', 'White'], logoUrl: './logos/sivas.png' },
  { id: 'umraniye', name: 'Ümraniyespor', colors: ['Red', 'White'], logoUrl: './logos/umraniye.png' },
  { id: 'van', name: 'Vanspor', colors: ['Red', 'Black'], logoUrl: './logos/van.png' },
  { id: 'eskisehir', name: 'Eskişehirspor', colors: ['Red', 'Black'], logoUrl: './logos/eskisehir.png' },
  { id: 'karsiyaka', name: 'Karşıyaka', colors: ['Green', 'Red'], logoUrl: './logos/karsiyaka.png' },
  { id: '24erzincan', name: '24 Erzincanspor', colors: ['Red', 'Black'], logoUrl: './logos/24erzincan.png' },
  { id: 'altinordu', name: 'Altınordu', colors: ['Red', 'Navy Blue'], logoUrl: './logos/altinordu.png' },
  { id: 'batman', name: 'Batman Petrolspor', colors: ['Red', 'White'], logoUrl: './logos/batman.png' },
  { id: 'elazig', name: 'Elazığspor', colors: ['Burgundy', 'White'], logoUrl: './logos/elazig.png' },
  { id: 'kastamonu', name: 'Kastamonuspor', colors: ['Red', 'Black'], logoUrl: './logos/kastamonu.png' },
  { id: 'ankaragucu', name: 'MKE Ankaragücü', colors: ['Yellow', 'Navy Blue'], logoUrl: './logos/ankaragucu.png' },
  { id: 'sanliurfa', name: 'Şanlıurfaspor', colors: ['Yellow', 'Green'], logoUrl: './logos/sanliurfa.png' },
  { id: 'adanaspor', name: 'Adanaspor', colors: ['Orange', 'White'], logoUrl: './logos/adanaspor.png' },
  { id: 'yenimalatya', name: 'Yeni Malatyaspor', colors: ['Yellow', 'Black'], logoUrl: './logos/yenimalatya.png' },
  { id: 'giresun', name: 'Giresunspor', colors: ['Green', 'White'], logoUrl: './logos/giresun.png' },
  { id: 'orduspor', name: 'Orduspor 1967', colors: ['Purple', 'White'], logoUrl: './logos/orduspor.png' },
  { id: 'altay', name: 'Altay', colors: ['Black', 'White'], logoUrl: './logos/altay.png' },
  { id: 'balikesir', name: 'Balıkesirspor', colors: ['Red', 'White'], logoUrl: './logos/balikesir.png' },
  { id: 'bucaspor', name: 'Bucaspor 1928', colors: ['Yellow', 'Navy Blue'], logoUrl: './logos/bucaspor.png' }
];
